# Generated by Django 5.2.8 on 2025-11-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price_in_billions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_district', models.CharField(max_length=100)),
                ('area_sqm', models.IntegerField()),
                ('alley_width_meters', models.FloatField(help_text='Width of the ngo/hem in front of house')),
                ('is_legal_clear', models.BooleanField(default=False, help_text='Is the Red Book (So Do) ready?')),
            ],
        ),
    ]
