# Generated by Django 5.2.8 on 2025-11-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ai_description',
            field=models.TextField(blank=True, help_text='Generated by OpenAI', null=True),
        ),
    ]
