# Generated by Django 5.2.8 on 2025-11-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_property_ai_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
    ]
