from django.db import models

class Property(models.Model):
    # This is how we made our money: structured data.
    title = models.CharField(max_length=200)
    price_in_billions = models.DecimalField(max_digits=10, decimal_places=2) 
    location_district = models.CharField(max_length=100) # e.g., "District 1", "Thao Dien"
    area_sqm = models.IntegerField()
    
    # The "Secret Sauce" fields (Things regular agents miss)
    alley_width_meters = models.FloatField(help_text="Width of the ngo/hem in front of house")
    is_legal_clear = models.BooleanField(default=False, help_text="Is the Red Book (So Do) ready?")
    ai_description = models.TextField(blank=True, null=True, help_text="Generated by OpenAI")
    # upload_to='properties/' puts images in a subfolder "media/properties/"
    main_photo = models.ImageField(upload_to='properties/', blank=True, null=True)
    
    def __str__(self):
        return f"{self.title} - {self.price_in_billions} Billion VND"
    
class Inquiry(models.Model):
    # Who is asking?
    listing = models.ForeignKey(Property, on_delete=models.CASCADE) # Links the lead to the specific house
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=20) # Essential for Vietnam market (Zalo)
    message = models.TextField(blank=True)
    contact_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Lead from {self.name} for {self.listing.title}"